apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: genai-spot-pod
  name: genai-spot-pod-test
  namespace: genai-spot-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genai-spot-pod
  template:
    metadata:
      labels:
        app: genai-spot-pod
    spec:
      serviceAccountName: vertex-autopilot-sa
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
        cloud.google.com/gke-spot: "true"
      terminationGracePeriodSeconds: 25
      containers:
      - image: us-west1-docker.pkg.dev/vertex-ai-project-here/genai-spot-pod/genai-spot-pod@sha256:71ebe64f17355ac5cbf4823ea92da2b0c2923ce8628a26b0344f10c819b41e20
        name: spot-pod
        args:
          - sh
          - -c
          - /opt/venv/bin/python3 /tmp/app/wsgi.py
        env:
          - name: BQ_TABLE
            value: 'bigquery-project-here.genai_spot_pod.document-summaries'
          - name: PUBSUB_TOPIC
            value: 'genai-spot-pod-test-1'
          - name: PUBSUB_SUBSCRIBER
            value: 'genai-spot-pod-sub-1'
        ports:
        - containerPort: 8080
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 15
          httpGet:
            path: /healthz
            port: 8080
        resources:
          requests:
            cpu: 100m
            memory: 512Mi